merge: Sun Apr  9 22:04:18 PDT 2023

diff --git a/tools/scripts/install_app_dependencies b/tools/scripts/install_app_dependencies
--- a/tools/scripts/install_app_dependencies
+++ b/tools/scripts/install_app_dependencies
@@ -1,6 +1,9 @@
 #!/bin/bash
-# This script checks for Python and Doppler CLI installations and installs them if necessary.
+# This script checks for Python, Doppler CLI, pm2 installations and installs them if necessary.
 # It also runs `yarn install --no-interactive`.
+
+# Exit the script if any command fails
+set -e
 
 # Update package lists
 echo "Updating package lists..."
@@ -43,25 +46,36 @@ else
   echo "Doppler CLI already installed."
 fi
 
+# Check for pm2 installation
+echo "Checking for pm2 installation..."
+pm2_installed=$(which pm2)
 
-# install docker and docker-compose
+if [ -z "$pm2_installed" ]; then
+  # Install pm2 if not found
+  echo "pm2 not found, installing..."
+  yarn global add pm2
+else
+  echo "pm2 already installed."
+fi
+
+# Install docker and docker-compose
 echo "Installing docker and docker-compose..."
 sudo yum install -y docker
 sudo usermod -a -G docker ec2-user
 id ec2-user
 newgrp docker
-wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) 
-sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/local/bin/docker-compose
+sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
 sudo chmod -v +x /usr/local/bin/docker-compose
 # start docker
 sudo service docker start
 
 # Run yarn install
 echo "Running 'yarn install --no-interactive'..."
-yarn install --no-interactive
 
-# build
-echo "Running 'yarn build'..."
-yarn apps:build
+(
+  cd /home/ec2-user/app &&
+  yarn cache clean &&
+  yarn install --no-interactive
+)
 
 echo "Script completed."
diff --git a/tools/scripts/start_server b/tools/scripts/start_server
--- a/tools/scripts/start_server
+++ b/tools/scripts/start_server
@@ -2,6 +2,13 @@
 # This script checks if Nginx is installed, installs it if necessary,
 # starts the Nginx server with a given configuration file, and starts all applications
 
+# Kill all running applications
+echo "Killing all running applications..."
+pkill -f "yarn apps:start"
+
+# Exit the script if any command fails
+set -e
+
 wait_for_port() {
   local port=$1
   local timeout=$2
@@ -22,7 +29,8 @@ fi
 
 # Start local Mongo and Redis instances using Docker Compose
 echo "Starting local Mongo and Redis instances..."
-docker-compose -f /home/ec2-user/app/docker-compose.prod.yml up -d
+docker_compose_path="/home/ec2-user/app/docker-compose.prod.yml"
+docker-compose -f $docker_compose_path up -d
 
 # Wait for Mongo and Redis to be ready
 echo "Waiting for Mongo and Redis to start listening on ports 27017 and 6379..."
@@ -31,8 +39,10 @@ wait_for_port 6379 60
 
 # Start all applications
 echo "Starting all applications..."
-cd /home/ec2-user/app 
-yarn apps:start > app_start.log 2>&1 &
+# stop apps for rebuild
+pm2 stop /home/ec2-user/app/ecosystem.config.js --user ec2-user 
+(cd /home/ec2-user/app/apps/client && yarn build)
+pm2 startOrReload /home/ec2-user/app/ecosystem.config.js --interpreter $(which node) --update-env --env production --user ec2-user --log-date-format "YYYY-MM-DD HH:mm:ss.SSS"
 
 # Wait for the applications to start listening on their respective ports
 echo "Waiting for applications to start listening on ports 7000, 8080, and 3000..."
@@ -42,16 +52,19 @@ wait_for_port 3000 30
 
 nginx_conf_file="/home/ec2-user/app/conf/nginx.conf"
 
-# Start Nginx with the specified configuration file
-echo "Starting Nginx with the provided configuration file..."
-sudo fuser -k 80/tcp
-sudo systemctl stop nginx
-sudo nginx -c $nginx_conf_file
+# Check if Nginx is running
+if pgrep nginx >/dev/null 2>&1; then
+  echo "Nginx is running. Reloading the configuration file..."
+  sudo nginx -c $nginx_conf_file -s reload
+else
+  echo "Nginx is not running. Starting Nginx with the provided configuration file..."
+  sudo nginx -c $nginx_conf_file
+fi
 
 # Check if Nginx started successfully
 if [ $? -eq 0 ]; then
-  echo "Nginx started successfully."
+  echo "Nginx operation completed successfully."
 else
-  echo "Failed to start Nginx."
+  echo "Failed to start or reload Nginx."
   exit 1
 fi
